### ISSUE TITLE
[Suggestion] Make a option to change the server invite of extensions

### ISSUE THREAD

**Issue by MatadorProBr** [6ixfalls/RPresence#1]
Make a option that can change the server invite of extensions, like: RoPro that have the same function that RoGold haves

**Comment by 6ixfalls** [comment]
RoPro uses an API to generate join links, I'll see what I can do.

**Comment by 6ixfalls** [comment]
I don't think this is legally possible, due to RoPro's terms of service- I don't think I'm allowed to use their API without express permission. I'll take a look to see what I can do to ask, but if not then this won't be possible.

**Comment by MatadorProBr** [comment]
> I don't think this is legally possible, due to RoPro's terms of service- I don't think I'm allowed to use their API without express permission. I'll take a look to see what I can do to ask, but if not then this won't be possible.

It seems that they agree with the use of their API on this project:
![image](https://user-images.githubusercontent.com/71022656/152646644-3040b8c7-cbd8-45c6-9faf-62e3816928d9.png)

Just to proof I will put the links of the messages so if you are in the RoPro Discord, you can see the messages on Discord only clicking on the link:

My message: https://discord.com/channels/786664487234699306/786666180618223697/937377462973779988
Response from the RoPro creator: https://discord.com/channels/786664487234699306/786666180618223697/939413791010074694

**Comment by 6ixfalls** [comment]
Looks fine then; I'll add a RoPro invite link version soon.

**Comment by 6ixfalls** [comment]
Added to latest release of RPresence.
